### PR TITLE
guess at re-enabling density inversion

### PR DESCRIPTION
**Pull request by BillMills**
Hi @castelao - per my comments in https://github.com/IQuOD/AutoQC/pull/259#issuecomment-711052578, I'm not sure how to run an Argo density inversion test since the case was removed in CoTeDe commit https://github.com/castelao/CoTeDe/commit/6f26a23974201df25dc15001dbf1ac6885e7cbe0. In this PR I _guess_ that the `DensityInversion` class works the same as most other CoTeDe QC tests, include it in catalog of tests in `qc.py`, and make it take a `QCCheckVar` argument and use the boilerplate init functions. Doing so allows the test to run and produce qualitatively reasonable (though still different from previous CoTeDe versions) results in AutoQC's test suite.

Let me know if this is completely wrong and there's another way to run the density inversion QC.

### CODE REVIEW

**Comment by castelao** [comment]
Thanks @BillMills ! You are in the right direction. I have a bunch of refactoring to push, and that's the reason that I haven't fixed this issue before. Let's use your PR, but I suggest some small changes. I'll address them in the review.

Thank you!

**Review by castelao — CHANGES_REQUESTED** [review]
Hi Bill. Thank you very much for your time. The density inversion should use QCCheck since the test doesn't depend/change on the variable being tested. This concept will be used in the near future. For now, we can resolve this with a try/except in the qc.py.

**Comment by castelao** [comment]
I forgot to mention, please include in your PR one line at the bottom of AUTHORS.rst (contributors) with something like:

@BillMills: PR #47, (short description)

Thanks!

**Comment by BillMills** [comment]
Hi @castelao, thanks for your feedback - your suggestions are implemented in 2e05286, please let me know if I missed anything.

**Review by castelao — APPROVED** [review]
Nice! Thank you very much @BillMills.

**Review by castelao — APPROVED** [review]

**Comment by BillMills** [comment]
Excellent - let me know when CoTeDe gets bumped on PyPI with this and your other changes, and we'll pull this into AutoQC.

**Pull request merged**
